os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b master
  - cd ./flutter/
  - git checkout 2.0.4
  - cd ..
  - ./flutter/bin/flutter doctor
script: 
  - ./flutter/bin/flutter packages pub get
  - ./flutter/bin/flutter packages pub run build_runner build
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
