include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - annotate_overrides
    - file_names
    - hash_and_equals
    - prefer_is_not_empty
    - sort_pub_dependencies 
    - unnecessary_statements
