name: initiative_tracker
description: A battle tracker for tabletop RPGs.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.0+250

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  equatable: ^2.0.0
  flex_color_picker: ^2.0.1
  flutter_bloc: ^7.0.0
  flutter_markdown: ^0.6.1
  json_annotation: ^4.0.1
  moor: ^4.2.1
  moor_flutter: ^4.0.0
  numberpicker: ^2.0.1
  package_info: ^2.0.0 
  path: ^1.7.0
  path_provider: ^2.0.1
  pref: ^2.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.4.1
  url_launcher: ^6.0.3

dependency_overrides:
  args: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
  markdown: ^4.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  async: ^2.4.2
  bloc_test: ^8.0.0
  build_runner: ^1.11.1
  json_serializable: ^4.0.1
  mockito: ^5.0.4
  moor_generator: ^4.2.1
  sqflite_common_ffi: ^2.0.0
  test: ^1.15.7

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/help/
    - assets/images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
